# Generische Konfiguration für den SCON GPTCache-Proxy
embedding:
  huggingface

embedding_config:
  model: 'sentence-transformers/all-MiniLM-L6-v2'

storage_config:
  data_dir:
    gptcache_data
  manager:
    sqlite,faiss
  vector_params:
    dimension: 1024

evaluation: 
  distance

evaluation_config:

pre_function:
  get_prompt

post_function:
  first

config:
  similarity_threshold: 0.95
  enable_token_counter: true