# Generische Konfiguration für den SCON GPTCache-Proxy
embedding:
  huggingface

embedding_config:
  model: 'microsoft/harrier-oss-v1-270m'

storage_config:
  data_dir:
    gptcache_data
  manager:
    sqlite,faiss
  vector_params:
    dimension: 640

evaluation: 
  distance

evaluation_config:

pre_function:
  get_liva_content

post_function:
  first

config:
  similarity_threshold: 0.85
  enable_token_counter: false